services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: job_automation_bot
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
      # /path/to/cv-file.md:/app/data/cv.md:ro MUST BE DEFINED IN docker-compose.override.yml
    env_file:
      - .env
    ports:
      - "${PORT:-8000}:${PORT:-8000}"    
    command: uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000} --reload