services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        - LLM_ENGINE=${LLM_ENGINE}
    container_name: job_automation_bot
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    env_file:
      - .env
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    command: uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000} --reload